version: '3.8'

services:
  postgres_db:
    image: postgres:13
    container_name: postgres_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: sales_user
      POSTGRES_PASSWORD: sales_password
      POSTGRES_DB: sales_db
    volumes:
      - ./data/postgres:/var/lib/postgresql/data  # Persist data
      - ./sql:/docker-entrypoint-initdb.d         # Initialize database with SQL scripts and sample data

  minio:
    image: minio/minio
    container_name: datalake_minio
    ports:
      - "9000:9000"  # Expose MinIO API
      - "9001:9001"  # Expose MinIO Console
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    volumes:
      - ./data/minio:/data  # Persist MinIO data
    command: server /data --console-address ":9001"  # Start MinIO server with console

  kafka:
    image: 'bitnami/kafka:latest' # Or a specific version like 'bitnami/kafka:3.7.0'
    container_name: kafka_broker
    ports:
      - "9092:9092" # For client connections
      - "9093:9093" # For controller communication (internal, but exposed for clarity)
    environment:
      # --- KRaft Mode Configuration ---
      KAFKA_CFG_NODE_ID: 1 # Unique ID for this Kafka node
      KAFKA_CFG_PROCESS_ROLES: controller,broker # This node acts as both controller and broker
      KAFKA_CLUSTER_ID: "lFUnmXIXSZ6V4bSjMztclQ" # one time generated cluster ID
      KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093 # Node ID @ ServiceName:ControllerPort
      KAFKA_CFG_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093 # Broker listener, Controller listener
      KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,CONTROLLER://kafka:9093 # For external/internal client connections
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_CFG_CONTROLLER_LISTENER_NAMES: CONTROLLER
      ALLOW_PLAINTEXT_LISTENER: "yes" # Essential for plaintext connections
      # --- Persistence for Kafka ---
      KAFKA_CFG_LOG_DIRS: /opt/bitnami/kafka/data/kraft_logs # Ensure persistent logs for KRaft
    volumes:
      - ./data/kafka:/opt/bitnami/kafka/data # Persistent data volume for Kafka logs/metadata
